export { default as VelocityPaintRefract } from './VelocityPaintRefract';
export { default as R3VelocityPaintRefract } from './R3VelocityPaintRefract';
export { default as VelocityPaintIridescence } from './VelocityPaintIridescence';
export { default as R3VelocityPaintIridescence } from './R3VelocityPaintIridescence';
export { default as VelocityPaintOil } from './VelocityPaintOil';
export { default as R3VelocityPaintOil } from './R3VelocityPaintOil';
export { VelocityPaintEngine, VP_DEFAULTS } from './velocityPaintEngine';
export { VelocityPaintIridescenceEngine, VP_IRIDESCENCE_DEFAULTS } from './VelocityPaintIridescenceEngine';
export { VelocityPaintOilEngine, VP_OIL_DEFAULTS } from './VelocityPaintOilEngine';
export type { VPConfig } from './velocityPaintEngine';
export type { VPIridescenceConfig } from './VelocityPaintIridescenceEngine';
export type { VPOilConfig } from './VelocityPaintOilEngine';
